name = "gleam_time"
version = "1.8.0"
description = "Clock and calendar functionality (macabre python-target port of gleam_time)"

licences = ["Apache-2.0"]
repository = { type = "github", user = "dusty-phillips", repo = "macabre_gleam_time" }

[dependencies]
gleam_stdlib = { git = "git@github.com:dusty-phillips/macabre_stdlib.git", ref = "main" }

[dev-dependencies]
gleeunit = { git = "git@github.com:dusty-phillips/macabre_gleeunit.git", ref = "main" }
